name: release

on:
  release:
    types: [released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libxml2-utils pandoc
        curl -sSL https://install.python-poetry.org | python3 -
        pip install --upgrade pip
        pip install -e ".[docs, dev]"
        pip install pyg_lib torch_scatter==2.1.1 torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cpu.html

    
    - name: Build package
      run: |
        poetry build
        ls -lh dist
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}